version: '3.8'

services:
  web:
    build: .
    command: uv run config.asgi:application --host 0.0.0.0 --port 8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      DJANGO_SETTINGS_MODULE: config.settings.base
      DJANGO_ENV: dev

  db:
    image: postgres:17-alpine
    environment:
      POSTGRES_DB: cashflowr
      POSTGRES_USER: cashflowr_user
      POSTGRES_PASSWORD: changeme
    volumes:
      - postgres_data:/var/lib/postgresql/data/

volumes:
  postgres_data: